#!/bin/bash

read -e -p "Define Dotfiles Directory : ~/" -i "dotfiles" pathInstall

echo ""

pathInstall = $HOME/$pathInstall

echo $pathInstall
echo "**** Download Dotfiles Repository"

git clone https://github.com/jestebanrods/dotfiles $pathInstall

echo ""

cd $pathInstall
chmod +x install

echo ""
echo ""
echo -e "**** Installing Dotfiles"

./.mdot/install

echo ""
echo -e "**** Install Dependencies"

echo ""
echo -e "**** Create Symbolic Links"

ln -sf $DOTFILES/editors/nvim $HOME/.config/nvim
ln -sf $DOFTLIES/shell/tmux/.tmux.conf $HOME/.tmux.conf
