#!/bin/bash

read -e -p "Define directory to save dotfiles :~/" -i "Documents/Code/jestebanrods/repos/dotfiles" path_install

echo ""

# path_install = "~/$path_install"

echo ~/$path_install
echo "**** Download repository dotfiles"

git clone https://github.com/jestebanrods/dotfiles ~/$path_install

echo ""

cd ~/$path_install
chmod +x install

echo ""
echo ""
echo -e "**** Installing dotfiles "

./install
source ~/.bashrc

echo ""
echo -e "**** Create Symbolic Links"

ln -sf $MDOT_BIN/editors/nvim $HOME/.config/nvim
ln -sf $MDOT_BIN/shell/tmux/.tmux.conf $HOME/.tmux.conf
