#!/bin/bash

C_RED='\033[0;31m'
C_NC='\033[0m'

function i_br()
{ 
    echo "" 
}

function i_read()
{
    message=$(printf " ${C_RED}===>${C_NC} $1")
    shift
    read -e -p "$message" $@
    i_br
}

function i_echo()
{
    printf "$1\n"
}

function i_mdot_title()
{
    printf "${C_RED}****${C_NC} $1\n"
}

function i_mdot_err()
{
    printf "🚫🚫 $1\n"
}

function i_mdot_success()
{
    printf "✅✅ $1\n"
}

function i_mdot_info()
{
    printf "ℹ️ ℹ️ $1\n"
}
function i_mdot_output()
{
    printf "⏩⏩ $1\n"
}

function i_mdot_abort()
{
    printf "⏹️  ⏹️  Stop Execution\n"
}

function i_mdot_pwd()
{
    cd $MDOT_PWD
}

function i_mdot_rm()
{
    rm -f "$1" > /dev/null
}

function i_mdot_has_error()
{
    lines=$(echo "$1" | wc -l)
    firstLine=$(echo "$1" | head -1)

    if [ "$firstLine" = true ] && [ "$lines" = 2 ]; then
        echo "$1" | tail +2
    fi
}

function mdot-core-clear(){
    unset -f i_echo
    unset -f i_read
    unset -f i_br
    unset -f mdot-core-clear
}

function m-kill-port () {
    fuser -k -n tcp $@
}

function m-grep-line()
{
    grep -n $@ | awk -F ":" '{ print $1 }' | head -1
}

function i_mdot_tmp()
{
    mkdir -p $MDOT_TMP
    mkdir -p "$MDOT_TMP/coverage"
    mkdir -p "$MDOT_TMP/composer"
    gitignore="$MDOT_TMP/.gitignore"
    rm -f 
    echo "*" > $gitignore
}
