#!/bin/bash

MDOT_INI="$MDOT_BIN/.mdot/ini"

source $MDOT_BIN/.env
source $MDOT_BIN/.mdot/core
source $MDOT_BIN/.mdot/loader

MDOT_PWD=$PWD
MDOT_TMP="mdot-temp"

MDOT_MODULES=$MDOT_BIN/lib;

MDOT_HELP="$MDOT_BIN/help";
MDOT_HELP_CMDS="$MDOT_HELP/.commands"
MDOT_HELP_LIST="$MDOT_HELP/.commands/.list";

mdot-loader-imports
mdot-loader-custom-imports

if ! [ -f $MDOT_HELP_LIST ]; then
    mdot-loader-wikis
fi

mdot-core-clear
mdot-loader-clear

function mdot-clear()
{
    if [ -d "tests-bk" ]; then
        echo "Replacement tests/ With tests-bk/"
        read -e -p "Do You Continue (Y) ? : " ok

        if [ "$ok" = "Y" ]; then
            rm -r "tests"
            mv tests-bk tests
        fi
    fi

    if [ -f "phpunit-bk.xml" ]; then
        mv phpunit-bk.xml phpunit.xml
    fi

    rm -rf $MDOT_TMP
}

function mdot-help()
{
    cd $MDOT_HELP_CMDS

    if [ "$1" ]; then
        cat $1
    else
        METHOD_NAME=$(ls -1 \
            | fzf --color="light" --preview="head {}"
        )

        if test -f "$METHOD_NAME"; then
            cat $METHOD_NAME
        fi
    fi

    i_mdot_pwd
}
