#!/bin/bash

function mdot-reload()
{
    rm $MDOT_HELP_LIST
    source $MDOT_BIN/.mdot/core
    echo "🚀🚀🚀 MDOT Reload"
    source $MDOT_INI
}

function mdot-loader-imports()
{
    for fileSource in $(find "$MDOT_MODULES" -type f); do 
        source $fileSource
    done
}

function mdot-loader-cmds()
{
    rm -r $MDOT_HELP_CMDS &> /dev/null
    mkdir -p $MDOT_HELP_CMDS &> /dev/null
    echo "" > $MDOT_HELP_LIST

    for moduleFile in $(find "$MDOT_MODULES" -type f); do 
        grep -n 'function m-' $moduleFile | while read -r actualLine; do
            lineNumPos=$(echo $actualLine | awk -F ":" '{ print $1 }')
            METHOD_NAME=$(tail +$lineNumPos $moduleFile \
                | head -1 \
                | awk -F "function " '{ print $2 }' \
                | awk -F "\(\)" '{ print $1 }'
            )
            echo "$METHOD_NAME" >> $MDOT_HELP_LIST
        done
    done
}

function mdot-loader-wikis()
{
    mdot-loader-cmds

    for METHOD_NAME in $(grep -E ".+" $MDOT_HELP_LIST); do
        moduleName=$(echo $METHOD_NAME \
            | awk -F "-" '{ print $2 }'
        )

        FILE_MODULE_WIKI="$MDOT_HELP/$moduleName"
        FILE_METHOD_WIKI="$MDOT_HELP_CMDS/$METHOD_NAME"

        echo -e "Not Documentation Available." > "$FILE_METHOD_WIKI"

        if [ -f "$FILE_MODULE_WIKI" ]; then
            LINE_INI=$(m-grep-line $METHOD_NAME: $FILE_MODULE_WIKI)
            if [ "$LINE_INI" ]; then
                LINE_END=$(tail +$LINE_INI $FILE_MODULE_WIKI | m-grep-line '^$')
                LINE_END=$(( LINE_END + LINE_INI - 2))
                LINE_INI=$(( LINE_INI +1 ))
                m-text-blines $LINE_INI $LINE_END $FILE_MODULE_WIKI > $FILE_METHOD_WIKI
            fi
        fi
    done
}

function mdot-loader-clear(){
    unset -f mdot-loader-imports
    unset -f mdot-loader-cmds
    unset -f mdot-loader-wikis
    unset -f mdot-loader-clear
    unset -f mdot-loader-custom-imports
}

function mdot-loader-custom-imports()
{
    if [[ $MDOT_CUSTOM_LIBRARIES ]]; then
        path="$MDOT_BIN/$MDOT_CUSTOM_LIBRARIES"
        for customLib  in $(ls -1 $path); do
            source "$path/$customLib"
        done
    fi
}

function m--arg-param()
{
    echo "$1" | awk -F "=" '{ print $1 }'
}

function m--arg-value()
{
    echo "$1" | awk -F "=" '{ print $2 }'
}
