#!/usr/bin/env bash

function m-rofi-merqueo-repos()
{
    ls $HOME/Documents/Code/merqueo/repos | rofi -show -dmenu -i | xargs -I_ code $HOME/Documents/Code/merqueo/repos/_
}

function m-rofi-active-windows()
{
    rofi -show
}
