# instala php 
#
### UBUNTU 18.04
#
## Instalar php 7.3
# ansible-playbook 52_php.yml
#
## Instalar php 7.4 en Ubuntu 18.04
# ansible-playbook 52_php.yml --extra-vars "PHP_VERSION=7.4"
#
### UBUNTU 20.04 NO SIRVE, la receta para ubuntu 20 no sirve
#
## Instalar php 7.3
# ansible-playbook 52_php.yml --extra-vars "UBUNTU=focal"
#
## Instalar php 7.4 en Ubuntu 18.04
# ansible-playbook 52_php.yml --extra-vars "PHP_VERSION=7.4 UBUNTU=focal"
#

- name: install php 
  hosts: localhost
  become: true
  
  vars_files: 
    - base.yaml
  
  vars:
    PHP_VERSION: 8.0
    UBUNTU: jammy

  tasks:
  - name: 10 | add apt key
    apt_key:
      url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x4F4EA0AAE5267A6C
      state: present
  
  - name: 10 | add ondrej php repository
    apt_repository:             
      repo: "deb http://ppa.launchpad.net/ondrej/php/ubuntu {{UBUNTU}} main"
      state: present
      update_cache: yes
  
  - name: 10 | install PHP
    apt:
      name: "{{packages}}"
      update_cache: yes
      state: present
    vars:
      packages:
        - zip
        - imagemagick
        - sqlite3 
        - "php{{ PHP_VERSION }}-sqlite3"
        - "php{{ PHP_VERSION }}-cli"        
        - "php{{ PHP_VERSION }}-bcmath"
        - "php{{ PHP_VERSION }}-mbstring"
        - "php{{ PHP_VERSION }}-curl"
        - "php{{ PHP_VERSION }}-gmp"
        - "php{{ PHP_VERSION }}-xml"
        - "php{{ PHP_VERSION }}-mysql"
        - "php{{ PHP_VERSION }}-zip"
        - "php{{ PHP_VERSION }}-imagick"
        - "php{{ PHP_VERSION }}-intl"
        - "php{{ PHP_VERSION }}-xdebug"

  - name: 10 | Install apm
    apt:
      deb: https://github.com/elastic/apm-agent-php/releases/download/v1.4/apm-agent-php_1.4_all.deb

  - name: 10 | enable cli opcache
    lineinfile:
      path: "/etc/php/{{ PHP_VERSION }}/cli/conf.d/10-opcache.ini"
      line: opcache.enable_cli = 1

  - name: 10 | install composer
    get_url:
      url: https://getcomposer.org/download/1.10.22/composer.phar
      dest: /usr/sbin/composer
      checksum: sha256:6127ae192d3b56cd6758c7c72fe2ac6868ecc835dae1451a004aca10ab1e0700
      mode: 0555

- name: install composer deps
  hosts: localhost
  tasks:
  - name: 10 | instala paquetes globales
    composer:
      command: require
      arguments: "{{item}}"
      global_command: yes
    with_items:
      - friendsofphp/php-cs-fixer:2.19.0
    connection: local
  - name: 10 | config path composer
    lineinfile:
      path: "{{item}}"
      line: "export PATH=~/.config/composer/vendor/bin:$PATH"
    with_items:
      - ~/.bashrc
    connection: local
