- name: Configurar servidor de archivos
  hosts: local
  become: false
  vars:
    NFS_CLOUD_PATH: "{{ ansible_env.HOME }}/NAS-Cloud"
  tasks:
    - name: Instalar paquetes
      become: true
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - nfs-common
        - cifs-utils
        - samba-client

    - name: Asegurar que los directorios existen
      file:
        path: "{{ item }}"
        state: directory
        # mode: "0755"
      loop:
        - "{{ NFS_CLOUD_PATH }}"

    - name: Montar recurso NFS
      become: true
      mount:
        path: "{{ NFS_CLOUD_PATH }}"
        src: "192.168.1.79:/export/Cloud"
        fstype: nfs
        opts: "_netdev"
        state: present
