setup:
	ansible-playbook ./playbooks/setup.yaml --ask-become-pass

nas:
	ansible-playbook ./playbooks/nas.yaml --ask-become-pass

dns:
	ansible-playbook ./playbooks/dns.yaml --ask-become-pass

php:
	ansible-playbook ./playbooks/php.yaml --ask-become-pass

go:
	ansible-playbook ./playbooks/go.yaml --ask-become-pass

node:
	ansible-playbook ./playbooks/node.yaml --ask-become-pass
